import { shortenHexString } from '@/utils'

export const contractInfoLabelsData = [
    {
        name: 'address',
        value: shortenHexString(process.env.NEXT_PUBLIC_CONTRACT),
        href: `https://amoy.polygonscan.com/address/${process.env.NEXT_PUBLIC_CONTRACT}`,
    },
    {
        name: 'standard',
        value: 'ERC721A',
        href: 'https://www.erc721a.org/',
    },
    {
        name: 'network',
        value: 'Polygon Amoy Testnet',
    },
    {
        name: 'NFT price*',
        value: '0.0005 MATIC',
    },
    {
        name: 'generated by',
        value: 'thirdweb.com',
        href: 'https://thirdweb.com/',
    },
]
