import { shortenHexString } from '@/utils'
import Image from 'next/image'
import arrowExternalIcon from '@/assets/arrow-external.svg'

const Footer = () => {
    return (
        <footer className="max-w-full overflow-x-hidden bg-linen">
            <div className="mx-auto flex max-w-6xl gap-8 px-4 py-8">
                {/* smart contract info */}
                <div className="basis-1/2">
                    <div className="border bg-white p-2">
                        <h5 className="mb-1 text-2xl font-bold">
                            Smart Contract Info
                        </h5>
                        <span className="mb-[0.8rem] block border-b border-wenge/5"></span>
                        <p className="flex justify-between py-[0.1rem] text-xs font-bold">
                            <span className="inline-block pr-4">
                                SittingCats <sup>NFT</sup>
                            </span>
                            <span>2023</span>
                        </p>
                        <span className="mb-[0.1rem] block border-b-4 border-wenge pt-[0.2rem]"></span>
                        <ul className="text-xs">
                            <li className="flex justify-between border-b border-wenge py-[0.1rem]">
                                <span className="inline-block pr-4">
                                    address
                                </span>
                                <a
                                    className="inline-block"
                                    href="https://mumbai.polygonscan.com/address/0x2b2d8aA76E03FEdFd22E9B5E333F9EAE10488014#readContract"
                                    target="_blank"
                                    rel="noopener noreferrer"
                                >
                                    {shortenHexString(
                                        '0x2b2d8aA76E03FEdFd22E9B5E333F9EAE10488014'
                                    )}
                                </a>
                            </li>
                            <li className="flex justify-between border-b border-wenge py-[0.1rem]">
                                <span className="inline-block pr-4">
                                    standard
                                </span>
                                <a
                                    className="inline-block"
                                    href="https://www.erc721a.org/"
                                    target="_blank"
                                    rel="noopener noreferrer"
                                >
                                    ERC721A
                                </a>
                            </li>
                            <li className="flex justify-between  border-b border-wenge py-[0.1rem]">
                                <span className="inline-block pr-4">
                                    network
                                </span>
                                <span className="inline-block">
                                    Polygon Mumbai Testnet
                                </span>
                            </li>
                            <li className="flex justify-between  border-b border-wenge py-[0.1rem]">
                                <span className="inline-block pr-4">
                                    NFT price*
                                </span>
                                <span className="inline-block">0</span>
                            </li>
                            <li className="flex justify-between py-[0.1rem]">
                                <span className="inline-block pr-4">
                                    generated by
                                </span>
                                <a
                                    className="inline-block"
                                    href="https://thirdweb.com/"
                                    target="_blank"
                                    rel="noopener noreferrer"
                                >
                                    thirdweb.com
                                </a>
                            </li>
                        </ul>

                        <span className="mb-1 block border-b-4 border-wenge pt-1"></span>
                        <p className="text-[0.55rem]">
                            *Having enough MATIC balance for gas ensures you can
                            cover the transaction fees required to claim your
                            NFTs
                        </p>
                    </div>
                </div>
                {/* contact */}
                <div className="flex h-auto basis-1/2 flex-col pb-2 text-sm">
                    <div className="mb-2 flex">
                        <div className="mr-2 flex flex-col pt-2">
                            <div>
                                <h5 className="inline font-bold">Contact: </h5>
                                <p className="inline">
                                    whether you have inquiries or employment
                                    opportunities to discuss, feel free to get
                                    in touch!. You can visit link or scan this
                                    qr-code to go to my linkedin profile.
                                </p>
                            </div>
                            <p className="mt-auto pt-2 font-bold">
                                <a
                                    className="mb-1 inline-block underline-offset-2 hover:underline"
                                    href="https://www.linkedin.com/in/danilo-bozinovic/"
                                    target="_blank"
                                    rel="noopener noreferrer"
                                >
                                    <Image
                                        className="mr-[0.2rem] inline-block w-[0.9rem] pb-[0.2rem] text-moonstone"
                                        src={arrowExternalIcon}
                                        alt="icon of arrow in box"
                                    />
                                    linkedin
                                </a>
                                <br />
                                <a
                                    className="underline-offset-2 hover:underline"
                                    href="https://github.com/danilo-89"
                                    target="_blank"
                                    rel="noopener noreferrer"
                                >
                                    <Image
                                        className="mr-[0.2rem] inline-block w-[0.9rem] pb-[0.2rem] text-moonstone"
                                        src={arrowExternalIcon}
                                        alt="icon of arrow in box"
                                    />
                                    github
                                </a>
                            </p>
                        </div>

                        <Image
                            className="min-w-0 flex-shrink-0 flex-grow basis-auto self-baseline"
                            src="/qr-code.png"
                            width="125"
                            height="125"
                            alt="linkedin profile qrcode"
                        />
                    </div>
                    <p className="mt-auto">
                        My friend and colleague was also actively involved in
                        testing this project. Check it out here: [insert link]
                    </p>
                </div>
            </div>
        </footer>
    )
}

export default Footer
