import './globals.css';
import type { Metadata } from 'next';
import { Poppins, Yellowtail } from 'next/font/google';

export const poppins = Poppins({
	subsets: ['latin'],
	weight: ['400', '700'],
	variable: '--font-poppins',
});
export const yellowtail = Yellowtail({
	subsets: ['latin'],
	weight: ['400'],
	variable: '--font-yellowtail',
});

export const metadata: Metadata = {
	title: 'Sitting Cats NFT',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body
				className={`${poppins.variable} ${yellowtail.variable} text-wenge bg-champagne`}
			>
				{children}
			</body>
		</html>
	);
}
